module sr
{
	struct S1
	{
		long a;
		char b;
	};
	
	interface I2
	{
		long op();
	};

	interface I2Ext : I2
	{
		long opExt();
	};
	
    interface I1
    {
    	short op1(in long abc);
        string op2( in string text, inout string text2, out string text3, in S1 struct1);
        I2 getI2();
    };
};
