// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_DevManagerDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Laboratory;

public interface _DevManagerDel extends Ice._ObjectDel
{
    DevS[] getDevsInfo(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    DevS viewDev(String ID, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    String connect(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               ApplicationException;

    DevPrx reserveDev(String ID, String accessToken, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               ApplicationException;

    void relaseDev(String ID, String accessToken, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               ApplicationException;

    void disconnect(String accessToken, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               ApplicationException;

    StatePrx devState(String ID, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
