// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_StateDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Laboratory;

public interface _StateDel extends Ice._ObjectDel
{
    String[] states(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    void setState(String newState, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
