// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_Dev_operations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Laboratory;

public abstract class Callback_Dev_operations extends Ice.TwowayCallback
{
    public abstract void response(Operation[] __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        DevPrx __proxy = (DevPrx)__result.getProxy();
        Operation[] __ret = null;
        try
        {
            __ret = __proxy.end_operations(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
