// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `DevPrx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Laboratory;

public interface DevPrx extends Ice.ObjectPrx
{
    public DevS info();

    public DevS info(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_info();

    public Ice.AsyncResult begin_info(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_info(Ice.Callback __cb);

    public Ice.AsyncResult begin_info(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_info(Callback_Dev_info __cb);

    public Ice.AsyncResult begin_info(java.util.Map<String, String> __ctx, Callback_Dev_info __cb);

    public DevS end_info(Ice.AsyncResult __result);

    public void doOperation(String name, String[] params)
        throws BadOperation;

    public void doOperation(String name, String[] params, java.util.Map<String, String> __ctx)
        throws BadOperation;

    public Ice.AsyncResult begin_doOperation(String name, String[] params);

    public Ice.AsyncResult begin_doOperation(String name, String[] params, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_doOperation(String name, String[] params, Ice.Callback __cb);

    public Ice.AsyncResult begin_doOperation(String name, String[] params, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_doOperation(String name, String[] params, Callback_Dev_doOperation __cb);

    public Ice.AsyncResult begin_doOperation(String name, String[] params, java.util.Map<String, String> __ctx, Callback_Dev_doOperation __cb);

    public void end_doOperation(Ice.AsyncResult __result)
        throws BadOperation;

    public Operation[] operations();

    public Operation[] operations(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_operations();

    public Ice.AsyncResult begin_operations(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_operations(Ice.Callback __cb);

    public Ice.AsyncResult begin_operations(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_operations(Callback_Dev_operations __cb);

    public Ice.AsyncResult begin_operations(java.util.Map<String, String> __ctx, Callback_Dev_operations __cb);

    public Operation[] end_operations(Ice.AsyncResult __result);
}
