/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_amwj_StringUtilStats */

#ifndef _Included_edu_amwj_StringUtilStats
#define _Included_edu_amwj_StringUtilStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_amwj_StringUtilStats
 * Method:    getNumberOfCalls
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_amwj_StringUtilStats_getNumberOfCalls
  (JNIEnv *, jobject);

/*
 * Class:     edu_amwj_StringUtilStats
 * Method:    getNumberOfReplacements
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_amwj_StringUtilStats_getNumberOfReplacements
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
