/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_amwj_StringUtil */

#ifndef _Included_edu_amwj_StringUtil
#define _Included_edu_amwj_StringUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_amwj_StringUtil
 * Method:    replace
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_amwj_StringUtil_replace
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     edu_amwj_StringUtil
 * Method:    getStats
 * Signature: ()Ledu/amwj/StringUtilStats;
 */
JNIEXPORT jobject JNICALL Java_edu_amwj_StringUtil_getStats
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
